url: "" # ANSSL官网域名
baseurl: "" # 博客子路径
title: "ANSSL博客" # 网站标题
author: "ANSSL团队" # 作者名称
email: "support@anssl.cn" # 联系邮箱
description: >- # 网站描述
  ANSSL专业SSL证书服务博客，分享SSL证书知识、网络安全技术和HTTPS部署经验。
lang: zh-CN # 网站语言
#timezone: Asia/Shanghai # 时区

# Permalink设置
permalink: /:year/:month/:day/:title/ # 日期+标题格式
permalink_style: date # 使用日期样式

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

